name: Build

on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v3
        -   name: Set up Python 3.10
            uses: actions/setup-python@v3
            with:
                python-version: "3.10"

        -   name: Install Python dependencies
            run: |
                    python -m pip install --upgrade pip
                    pip install numpy

        -   name: Compile, install and test native-template
            working-directory: native-template
            run: |
                    pip install .
                    python -c "import native_template; assert native_template.hello_world()=='Hello World'"

        -   name: Compile, install and test numpy-template
            working-directory: numpy-template
            run: |
                    pip install .
                    python -c "import numpy_template, numpy as np; assert (numpy_template.eye(15) == np.eye(15)).all()"

        
        -   name: Compile, install and test torch-template
            working-directory: torch-template
            run: |
                    pip install torch==2.1.0
                    python -c "import torch
                    from torch.utils import cpp_extension
                    print('LIBTORCH_VERSION:', torch.__version__.split('+')[0])
                    print('LIBTORCH_CXX11:', torch._C._GLIBCXX_USE_CXX11_ABI)
                    for include_path in cpp_extension.include_paths():
                        print('LIBTORCH_INCLUDE:', include_path)
                    for library_path in cpp_extension.library_paths():
                        print('LIBTORCH_LIB:', library_path)"
                    export LIBTORCH_USE_PYTORCH=1
                    pip install .
                    python -c "import torch-template, torch; assert (torch.arange(10) + 1 == torch_template.add_one(torch.arange(10))).all()"

        
